import { writeFile } from 'node:fs/promises'
import type { Session } from 'electron'

/** The cookie fields we need (subset of Electron.Cookie). */
export interface CookieLike {
  name: string
  value: string
  domain?: string
  hostOnly?: boolean
  path?: string
  secure?: boolean
  httpOnly?: boolean
  session?: boolean
  expirationDate?: number
}

/**
 * Serialises cookies in the Netscape "cookies.txt" format read by yt-dlp:
 * domain, include-subdomains, path, secure, expiry, name, value (tab separated).
 */
export function toNetscape(cookies: CookieLike[]): string {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by Grabbit. Do not edit.', '']
  for (const c of cookies) {
    if (!c.domain || /[\t\n\r]/.test(c.name + c.value)) continue
    const domain = c.hostOnly ? c.domain.replace(/^\./, '') : c.domain.startsWith('.') ? c.domain : `.${c.domain}`
    const includeSub = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const expiry = c.session || !c.expirationDate ? 0 : Math.floor(c.expirationDate)
    const prefix = c.httpOnly ? '#HttpOnly_' : ''
    lines.push([prefix + domain, includeSub, c.path || '/', c.secure ? 'TRUE' : 'FALSE', String(expiry), c.name, c.value].join('\t'))
  }
  return lines.join('\n') + '\n'
}

/** Writes all cookies of `session` to `file`; returns false (and writes nothing) when there are none. */
export async function exportSessionCookies(session: Session, file: string): Promise<boolean> {
  const cookies = await session.cookies.get({})
  if (!cookies.length) return false
  await writeFile(file, toNetscape(cookies), { mode: 0o600 })
  return true
}
